### PR TITLE
Revisions in docs after testing on MIT slurm cluster

### PR DESCRIPTION
**Pull request by djarecka**
@zhao-cy - I've tested the example on our cluster and I added a few suggestions to the documentation. 

I think the most important is that some combination of the cluster settings might not work (setting `temporary_disk_space` leads to the error in my case). I've also specified the version of Singularity that I used for testing, since I had problem with building the singularity image from your docker image using my previously default version that was older.

Overall, I think the document looks great, the instructions are very detailed, so hopefully everyone should be able to follow!

Some additional comments/suggestions:

- any reason why you sometimes use `${PWD}` and sometimes `$PWD`?
- are you sure that ` Provide your OSF credentials (token) - this step is very important!`?  
- I've noticed that you provide information how to copy properly with vim to get proper yaml file. If you want to cover this perhaps you can provide an [online website to validate the yaml file](https://www.yamllint.com/)

### CODE REVIEW

**Comment by djarecka** [comment]
and this is the version of yaml file I was using, do you want me to add it somewhere?

```
singularity_run:
    --no-zipped: ""
    --dummy: "2"
    -v: ""

# Output foldername(s) to be zipped, and the BIDS App version to be included in the zip filename(s):
zip_foldernames:
    toybidsapp: "0-0-7"

# How much cluster resources it needs:
cluster_resources:
    interpreting_shell: /bin/bash
    hard_memory_limit: 2G
    number_of_cpus: 2
    hard_runtime_limit: 0:20:00
    customized_text: |
        #SBATCH -p gablab


# Necessary commands to be run first:
script_preamble: |
    module load openmind/singularity/3.9.5
    source /om2/user/djarecka/miniconda/bin/activate babs_ex

# Where to run the jobs:
job_compute_space: /om2/scratch/Fri/djarecka/babs_demo/comp
```

**Comment by zhao-cy** [comment]
Thank you so much @djarecka ! To answer your questions: 

- Ah I think `${PWD}` or `$PWD` are usually interchangable/does not matter I think; And it seems like I'll be more likely to use `${PWD}` when it's part of a full dir, e.g., `ria+file://${PWD}/my_BABS_project/output_ria#~data`. Anyway, if users just copy and paste the commands in the walkthrough, it should be fine as it has been tested by me, you and Sydney, so I probably won't further change to make them consistent.
- OSF credential: yeah I think setting that up is important. It was based on my experience or Sydney or Matt's experience, cannot remember exactly.
- YAML file validator is a good idea after users add any customized commands; I might suggest users not using `Reformat ` mode as it will largely change the YAML file.

**Comment by zhao-cy** [comment]
These are not needed for this example walkthrough, but just Dorota wanted to check if it's working or not:

```
    number_of_cpus: 2
    hard_runtime_limit: 0:20:00
    customized_text: |
        #SBATCH -p gablab
```

Only thing is to remove the `--tmp` command.

**Comment by zhao-cy** [comment]
Hi @djarecka! Just let you know that I eventually removed `temporary_disk_space` from the example YAML used in the example walkthrough, as it's not necessary for this toy BIDS App (confirmed on our CUBIC SGE cluster and MSI Slurm cluster, and your tests on MIT Slurm cluster too). I also made other modifications upon your revisions in the docs too.

**Comment by zhao-cy** [comment]
In this PR, @djarecka replicated the example walkthrough on their MIT OpenMind Slurm cluster. She and I made some changes in the docs:

- example walkthrough:
  - `temporary_disk_space` has been removed from the example YAML used in the example walkthrough
  - Generated directives from Slurm cluster has been added
  - What if singularity build was not successful: check singularity software version.
-  other part of the docs:
  - add a note re: `temporary_disk_space` in the `docs/source/preparation_config_yaml_file.rst`

**Pull request merged**
